added UBX_CFG_SMGR configuration support
sparkfun/SparkFun_u-blox_GNSS_Arduino_Library pull request #211
Opened 2024-03-05 22:43 UTC by dizcza

Sketch output:

```
UBX-CFG-SMGR:
 version 0 (0x00)
 minGNSSFix 5 (0x05)
 maxFreqChangeRate 30 (0x1e)
 maxPhaseCorrRate 80 (0x50)
 freqTolerance 250 (0xfa)
 timeTolerance 2000 (0x7d0)
 messageCfg:
   measInternal: 1
   measGNSS: 1
   measEXTINT0: 1
   measEXTINT1: 1
 maxSlewRate 10000 (0x2710)
 flags:
   disableInternal: 0
   disableExternal: 1
   preferenceMode: 0
   enableGNSS: 1
   enableEXTINT0: 0
   enableEXTINT1: 0
   enableHostMeasInt: 1
   enableHostMeasExt: 1
   useAnyFix: 1
   disableMaxSlewRate: 0
   issueFreqWarn: 1
   issueTimeWarn: 1
   TPCoherent: 2
   disableOffset: 0

UBX-CFG-SMGR successfully updated
```

----

I don't see any UBX messages from my device (they are set to echo on Serial) even though PPS is flashing and I have a fix (tried setting `minGNSSFix` to 1). Any clue?

2024-03-05 22:52 UTC, dizcza commented
In particular, no UBX-TIM-SMEAS messages - that's why I started figuring out the SMGR protocol.

2024-03-06 08:03 UTC, PaulZC requested changes
Hi Danylo (@dizcza ),

This is a useful PR, but it needs some changes... Thanks!

Best wishes,
Paul

2024-03-06 08:07 UTC, PaulZC commented
Hi Danylo (@dizcza ),

UBX-TIM-SMEAS is almost certainly disabled by default. You will need to enable it with CFG-MSG, or via u-center.

I hope this helps,
Paul

2024-03-06 08:21 UTC, dizcza commented on examples/Example33_TimeFreqSyncManager/Example33_TimeFreqSyncManager.ino
> +  ubxPacket customCfg = {0, 0, 0, 0, 0, (uint8_t*) &cfgSmgrPayload, 0, 0, SFE_UBLOX_PACKET_VALIDITY_NOT_DEFINED, SFE_UBLOX_PACKET_VALIDITY_NOT_DEFINED};
I also thought about it. But can it be the case? The unions are guarded with the corresponding uintX_t to pad the structure and even in the case of packing, the struct size will be at least the sum of its components.

2024-03-06 08:56 UTC, dizcza commented
> UBX-TIM-SMEAS is almost certainly disabled by default. You will need to enable it with CFG-MSG, or via u-center.

How to do this? I guess I need to simply call
```
myGNSS.setVal8(UBLOX_CFG_MSGOUT_UBX_TIM_SMEAS_I2C, 1);
```
but I cannot come up with a value for `UBLOX_CFG_MSGOUT_UBX_TIM_SMEAS_I2C` - I don't find any mention of how this key value is constructed in the specs datasheet.

![Screenshot from 2024-03-06 10-56-17](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/assets/7688337/5d6c73b8-d604-4f10-9b69-536c066b411c)

2024-03-06 09:29 UTC, PaulZC commented on examples/Example33_TimeFreqSyncManager/Example33_TimeFreqSyncManager.ino
> +  ubxPacket customCfg = {0, 0, 0, 0, 0, (uint8_t*) &cfgSmgrPayload, 0, 0, SFE_UBLOX_PACKET_VALIDITY_NOT_DEFINED, SFE_UBLOX_PACKET_VALIDITY_NOT_DEFINED};
It should work if the size of UBX_CFG_SMGR_data_t is correct... :-)
To check, ```print(sizeof(UBX_CFG_SMGR_data_t));``` should show 20.

But I am trying to remember what happens if a longer message - e.g. NAV PVT - arrives unsolicited (periodically) after the ```sendI2cCommand``` and before the ```waitForAckResponse``` is complete. I think the code will attempt to use cfgSmgrPayload to store the PVT message, causing an overrun.

For safety, please use a 'full size' payload like we do in the [examples](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/blob/9b27ef1cc1117eeb74a8572507b5cfecd921d5c1/examples/Example20_SendCustomCommand/Example20_SendCustomCommand.ino#L64-L73).

2024-03-06 09:34 UTC, dizcza commented
I think I managed to output TIM-SMEA but I get garbage on my Serial:

```
void enableMSG_TIM_SMEAS() {
  uint8_t customPayload[MAX_PAYLOAD_SIZE]; // This array holds the payload data bytes. MAX_PAYLOAD_SIZE defaults to 256. The CFG_RATE payload is only 6 bytes!

  ubxPacket customCfg = {0, 0, 0, 0, 0, customPayload, 0, 0, SFE_UBLOX_PACKET_VALIDITY_NOT_DEFINED, SFE_UBLOX_PACKET_VALIDITY_NOT_DEFINED};

  customCfg.cls = UBX_CLASS_CFG; // This is the message Class
  customCfg.id = UBX_CFG_MSG; // This is the message ID
  customCfg.len = 3; // Setting the len (length) to zero let's us poll the current settings
  customCfg.startingSpot = 0; // Always set the startingSpot to zero (unless you really know what you are doing)

  customPayload[0] = UBX_CLASS_TIM;
  customPayload[1] = 0x13;
  customPayload[2] = 1;    // rate in Hz (measurements per sec)

  // We also need to tell sendCommand how long it should wait for a reply
  uint16_t maxWait = 250; // Wait for up to 250ms (Serial may need a lot longer e.g. 1100)

  // Now we write the custom packet back again to change the setting
  if (myGNSS.sendCommand(&customCfg, maxWait) != SFE_UBLOX_STATUS_DATA_SENT) // This time we are only expecting an ACK
  {
    Serial.println(F("Could not update TIM-SMEAS MSG rate"));
  }
  else
  {
    Serial.println(F("TIM-SMEAS MSG rate successfully updated"));
  }

}
```

Is this because I pipe raw bytes to serial?
```
  myGNSS.setOutputPort(Serial);
```

2024-03-06 09:36 UTC, dizcza commented on examples/Example33_TimeFreqSyncManager/Example33_TimeFreqSyncManager.ino
> +  ubxPacket customCfg = {0, 0, 0, 0, 0, (uint8_t*) &cfgSmgrPayload, 0, 0, SFE_UBLOX_PACKET_VALIDITY_NOT_DEFINED, SFE_UBLOX_PACKET_VALIDITY_NOT_DEFINED};
all right, will do

2024-03-06 09:40 UTC, PaulZC commented
The LEA-M8F doesn't support the Configuration Interface. You will need to enable the message manually using ```configureMessage(UBX_CLASS_TIM, 0x13, COM_PORT_I2C, 1);```

The message is UBX binary format. It will contain unprintable characters. You could use a logic analyzer to view the bytes as HEX. Or write a very simple binary to HEX converter and run it on another board?

2024-03-06 09:45 UTC, PaulZC commented
Or - even better - use an FTDI (serial -> USB) cable, connect it to your PC and use u-center to display and decode the messages! ;-)

2024-03-06 09:47 UTC, PaulZC commented
Or - even better - close the serial monitor / terminal emulator and open u-center instead. It will be able to decode the UBX messages and display them correctly.

2024-03-06 10:02 UTC, dizcza commented
> The LEA-M8F doesn't support the Configuration Interface. You will need to enable the message manually using `configureMessage(UBX_CLASS_TIM, 0x13, COM_PORT_I2C, 1);`

This one-liner looks much simpler.

> Or - even better - close the serial monitor / terminal emulator and open u-center instead. It will be able to decode the UBX messages and display them correctly.

I'm on Ubuntu, I doubt the u-center supports Linux. Even if it does, I eventually need to be able to parse these messages on an ESP32 board via I2C.

Looks like I need to extend the `case UBX_CLASS_TIM` in the sources and add something similar to `packetUBXTIMTM2`.

2024-03-06 19:45 UTC, dizcza commented
All right, it was quite a change.

Now the example outputs TIM-SMEA messages:

```
UBX-TIM-SMEAS:
 version: 0
 numMeas: 4
 iTOW: 330285000
 sourceId 0:
   flags:
      freqValid 1
      phaseValid 1
   phaseOffsetFrac -75
   phaseUncFrac 102
   phaseOffset 2
   phaseUnc 8
   freqOffset -77
   freqUnc 93
 sourceId 1:
   flags:
      freqValid 1
      phaseValid 1
   phaseOffsetFrac -17
   phaseUncFrac 237
   phaseOffset 4
   phaseUnc 7
   freqOffset -36
   freqUnc 70
 sourceId 2:
   flags:
      freqValid 0
      phaseValid 0
   phaseOffsetFrac 0
   phaseUncFrac 0
   phaseOffset 0
   phaseUnc 0
   freqOffset 0
   freqUnc 0
 sourceId 3:
   flags:
      freqValid 0
      phaseValid 0
   phaseOffsetFrac 0
   phaseUncFrac 0
   phaseOffset 0
   phaseUnc 0
   freqOffset 0
   freqUnc 0
```

2024-03-06 19:46 UTC, dizcza commented
I added only one way to pass user callbacks, `setAutoTIMSMEAcallback`, not to overwhelm poor users with otherwise great API.

2025-07-30 09:41 UTC, PaulZC approved these changes

2025-07-30 09:48 UTC, merged

2025-07-30 09:58 UTC, PaulZC commented
I still don't have hardware to test this on. But your code looks good, and compiles OK. I'm happy to merge this into main.

I will merge #238 at the same time - as soon as the missing semicolons are added?! ;-)

2025-07-30 10:10 UTC, dizcza commented
Glad that it has finally completed its voyage.