UBX-NAV-TIMELS support added for leap second event
sparkfun/SparkFun_u-blox_GNSS_Arduino_Library pull request #25
Opened 2021-04-14 16:46 UTC by UT2UH

Provides leap second event info as SNTP Leap Indicator, time to a leap second event and the number of leap seconds since GPS epoch for applications like NTP server.

2021-04-14 17:23 UTC, PaulZC commented
Hi @UT2UH ,
This PR looks really nice - thank you!
The only thing that jumps out is that the library has a new ```end``` function which deletes all of the RAM allocated for message storage. We will need to include the TIMELS storage in there too. You are not using callbacks - which is OK - so the code will look the same as [moduleSWVersion and currentGeofenceParams](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/blob/master/src/SparkFun_u-blox_GNSS_Arduino_Library.cpp#L74-L84). Can you please add it? Thanks!
Best wishes,
Paul

2021-04-14 18:49 UTC, UT2UH commented
Hello @PaulZC , 
hope that is it. 
Thanks and regards!

2021-04-15 08:10 UTC, PaulZC commented on src/SparkFun_u-blox_GNSS_Arduino_Library.cpp
> +  if (packetUBXNAVTIMELS->moduleQueried.moduleQueried.bits.valid == false)
Hi @UT2UH ,
If you use ```.valid``` here to check if the currLs data has been read before, then if you call ```getLeapIndicator``` followed by ```getCurrentLeapSeconds``` then ```getCurrentLeapSeconds``` will always request fresh data (by calling ```getLeapSecondEvent```). I'm not sure if that is what you want? I suspect probably not?
My advice would be to change ```.valid``` in line 10415 to ```.currLs``` and then delete line 10417.
That way ```getLeapIndicator``` will only be called once if you call ```getLeapIndicator``` followed by ```getCurrentLeapSeconds``` or vice versa.
Please have a think about this. Thanks!
Paul

2021-04-15 08:31 UTC, PaulZC commented on src/u-blox_structs.h
> +  int8_t valid; // Validity flag, 1 = valid, otherwise 0
Hi @UT2UH ,
Looking at the ZED_F9P interface description, ```valid``` contains two bits (not one):

![image](https://user-images.githubusercontent.com/5690545/114838088-43b8b600-9dcc-11eb-9bd0-db7e87c8e8e1.png)

(Sometimes the ZED messages contain extra bits compared to the M8 family)
Can you please change ```valid``` into a union+struct? Something like:

```
  union
  {
    uint8_t all;
    struct
    {
      uint8_t validCurrLs : 1; // 1 = Valid current number of leap seconds value
      uint8_t validTimeToLsEvent : 1; // 1 = Valid time to next leap second event or from the last leap second event if no future event scheduled
    } bits;
  } valid;
```

This means you will need to change ```getLeapIndicator``` so it uses ```data.valid.bits.validCurrLs```.
Thanks!
Paul

2021-04-15 08:36 UTC, PaulZC commented on src/u-blox_structs.h
> +      uint32_t valid : 1;
Sorry - this needs to be:
```
uint32_t validCurrLs : 1;
uint32_t validTimeToLsEvent : 1;
```

2021-04-15 08:43 UTC, PaulZC requested changes
Hi @UT2UH ,
This is a really nice PR - thank you. You have followed the structure of the "auto" message code really well. I just have three comments (see above). Please take a look...
Thanks again,
Paul

2021-04-15 09:34 UTC, UT2UH commented
Hi @PaulZC !
Yep, you are right, including on my mindless copycat issues too... Strange that it worked somehow... )
Thank you very much for the help and for the great library!

2021-04-15 09:56 UTC, PaulZC commented
Thanks @UT2UH ,
Good use of those two valid bits! ;-)
Merging...
Thanks again,
Paul

2021-04-15 09:57 UTC, merged